/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async (knex) => {
  // Deletes ALL existing entries
  await knex.raw('ALTER SEQUENCE companies_id_seq RESTART WITH 1');

  return knex('companies').del()
    .then(function () {
      // Inserts seed entries
      return knex('companies').insert([
        { name: 'Management' },
        { name: 'House Keeping' },
        { name: 'Aerie' },
        { name: 'Aeropostale' },
        { name: 'Against All odds' },
        { name: 'American Eagle' },
        { name: 'Box Lunch' },
        { name: 'Champs' },
        { name: 'Clarks' },
        { name: 'Charlotte Russe' },
        { name: 'Express' },
        { name: 'Famous Footwear' },
        { name: 'Gap' },
        { name: 'H&M' },
        { name: 'Hollister' },
        { name: 'Hot Topic' },
        { name: 'Journeys' },
        { name: 'Journeys kidz' },
        { name: 'Old Navy' },
        { name: 'Lush' },
        { name: 'Pink' },
        { name: 'U.S.Polo Assin.' },
        { name: 'Uniqlo' },
        { name: 'Vans' },
        { name: 'Victoria’s Secret' },
        { name: 'Windsor Fashion' },
        { name: 'Xbelta' },
        { name: 'Zumiez' },
        { name: 'Laced Up' },
        { name: 'Ez Fix' },
        { name: 'Icing' },
        { name: 'Lids' },
        { name: 'Lovisa' },
        { name: 'Sunglass Hut' },
        { name: 'Foot Locker' },
        { name: 'Kids Foot Locker' },
        { name: 'Xsport Fitness' },
        { name: 'Olive Garden' },
        { name: 'Kpot' },
        { name: 'Sabrosito' },
        { name: 'Koi Sushi' },
        { name: 'Auntie Anne’s' },
        { name: 'Billy Beez' },
        { name: 'Charley’s Subs' },
        { name: 'Chicken Now' },
        { name: 'Chip city' },
        { name: 'Cinnabon' },
        { name: 'Crepes NYC' },
        { name: 'Frozen D Lite' },
        { name: 'Mama G’s Halal' },
        { name: 'Master Wok' },
        { name: 'Moe’s Southwest Grill' },
        { name: 'Nathan’s Famous' },
        { name: 'Sarku' },
        { name: 'Sbarro' },
        { name: 'Scotch Bonnet' },
        { name: 'Starbucks' },
        { name: 'Sweet & Sour' },
        { name: 'Thai max' },
        { name: 'Tiger King' },
        { name: 'Vr Theme Park' },
        { name: 'All About Toys' },
        { name: 'Gateway News' },
        { name: 'Rumi Life' },
        { name: 'Spencers' },
        { name: 'Bath & Body / Whitebarn Candle Co.' },
        { name: 'G.D. Palace' },
        { name: 'Kay Jewellers' },
        { name: 'Pandora' },
        { name: 'Pirecing Pagoda Kiosk' },
        { name: 'Swarovski' },
        { name: 'Zales' },
        { name: 'Mission Shoes' },
        { name: 'T-Mobile' },
        { name: 'Apple' },
        { name: 'Dental' },
        { name: 'Cohen’s' },
        { name: 'GNC' },
        { name: 'Perfumania' },
        { name: 'Premier Hair & Beauty' },
        { name: 'Royal Med Spa' },
        { name: 'Victoria Nail' },
        { name: 'Vista Eye Care' },
      ]);
    });
};
